/** Location-based SEO pages — local + service+city combinations */
export const LOCATION_PAGES = [
  {
    slug: 'astrologer-in-mumbai',
    city: 'Mumbai',
    region: 'Maharashtra',
    focus: 'Astrologer',
    title: 'Best Astrologer in Mumbai | Love & Relationship Expert – Dheeraj Shastri Ji',
    description: 'Top astrologer in Mumbai for love, marriage & career. Online consultation for Mumbai, Navi Mumbai & Thane. 15+ years · 5000+ clients · Results in 24 hrs.',
    h1: 'Best Astrologer in Mumbai – Love, Marriage & Life Guidance',
    intro: 'Searching for the best astrologer in Mumbai? Dheeraj Shastri Ji offers premium online Vedic astrology consultation for love problems, ex love back, marriage disputes, vashikaran, and career guidance — serving all of Mumbai and Maharashtra.',
    keywords: ['astrologer in Mumbai', 'best astrologer Mumbai', 'online astrologer Mumbai', 'jyotish Mumbai'],
  },
  {
    slug: 'astrologer-in-delhi',
    city: 'Delhi',
    region: 'Delhi NCR',
    focus: 'Astrologer',
    title: 'Best Astrologer in Delhi NCR | Love Back Specialist – Dheeraj Shastri Ji',
    description: 'Trusted astrologer in Delhi, Gurgaon, Noida & Faridabad. Love problem, ex love back, marriage & vashikaran consultation online. Free WhatsApp consultation.',
    h1: 'Best Astrologer in Delhi NCR – Relationship & Marriage Expert',
    intro: 'Delhi NCR residents trust Dheeraj Shastri Ji for accurate Vedic astrology — love back solutions, breakup recovery, intercaste marriage guidance, and husband-wife dispute remedies through confidential online consultation.',
    keywords: ['astrologer in Delhi', 'best astrologer Delhi NCR', 'online astrologer Delhi', 'relationship astrologer Delhi'],
  },
  {
    slug: 'astrologer-in-bangalore',
    city: 'Bangalore',
    region: 'Karnataka',
    focus: 'Astrologer',
    title: 'Best Astrologer in Bangalore | Online Love Astrologer – Dheeraj Shastri Ji',
    description: 'Top astrologer in Bangalore & Karnataka. Love problem solution, ex love back, kundli matching & vashikaran. Online WhatsApp consultation 24/7.',
    h1: 'Best Astrologer in Bangalore – Love & Marriage Specialist',
    intro: 'Bangalore clients consult Dheeraj Shastri Ji online for love astrology, marriage problems, career guidance, and spiritual healing — premium Vedic consultation without leaving home.',
    keywords: ['astrologer in Bangalore', 'best astrologer Bangalore', 'online astrologer Karnataka', 'love astrologer Bangalore'],
  },
  {
    slug: 'love-problem-solution-in-mumbai',
    city: 'Mumbai',
    region: 'Maharashtra',
    focus: 'Love Problem Solution',
    title: 'Love Problem Solution in Mumbai | Ex Love Back – Dheeraj Shastri Ji',
    description: 'Love problem solution in Mumbai by expert astrologer. Ex love back, breakup help, vashikaran & relationship remedies. Online consultation for all Mumbai.',
    h1: 'Love Problem Solution in Mumbai – Expert Astrologer',
    intro: 'Mumbai\'s most trusted love problem solution astrologer — helping couples reunite, resolve conflicts, and overcome family opposition through proven Vedic remedies. Consult from anywhere in Mumbai via WhatsApp.',
    keywords: ['love problem solution Mumbai', 'love problem solution in Mumbai', 'ex love back Mumbai', 'relationship astrologer Mumbai'],
  },
  {
    slug: 'vashikaran-specialist-in-delhi',
    city: 'Delhi',
    region: 'Delhi NCR',
    focus: 'Vashikaran Specialist',
    title: 'Vashikaran Specialist in Delhi | Love Vashikaran Expert',
    description: 'Vashikaran specialist in Delhi NCR for love, marriage & relationship problems. Ethical remedies by Dheeraj Shastri Ji. Confidential online consultation 24/7.',
    h1: 'Vashikaran Specialist in Delhi – Ethical Love Remedies',
    intro: 'Delhi NCR clients seeking a vashikaran specialist trust Dheeraj Shastri Ji for ethical, result-oriented spiritual remedies — love attraction, marriage harmony, and removal of relationship obstacles.',
    keywords: ['vashikaran specialist Delhi', 'vashikaran specialist in Delhi', 'love vashikaran Delhi', 'best vashikaran Delhi'],
  },
  {
    slug: 'love-astrologer-mumbai',
    city: 'Mumbai',
    region: 'Maharashtra',
    focus: 'Love Astrologer',
    title: 'Love Astrologer in Mumbai | Ex Love Back Specialist – Dheeraj Shastri Ji',
    description: 'Best love astrologer in Mumbai for ex love back, breakup help & vashikaran. Online consultation for relationship & marriage problems. Results in 24 hrs.',
    h1: 'Love Astrologer in Mumbai – Ex Love Back & Relationship Expert',
    intro: 'Looking for a trusted love astrologer in Mumbai? Dheeraj Shastri Ji offers confidential online consultation for ex love back, breakup recovery, vashikaran remedies, and marriage problem solutions.',
    keywords: ['love astrologer in Mumbai', 'ex love back specialist Mumbai', 'vashikaran specialist Mumbai'],
  },
  {
    slug: 'love-astrologer-delhi',
    city: 'Delhi',
    region: 'Delhi NCR',
    focus: 'Love Astrologer',
    title: 'Love Astrologer in Delhi | Ex Love Back Solution – Dheeraj Shastri Ji',
    description: 'Top relationship astrologer in Delhi NCR. Ex love back, love marriage, breakup help & online vashikaran consultation. 15+ years experience.',
    h1: 'Love Astrologer in Delhi – Ex Love Back & Marriage Problem Expert',
    intro: 'Delhi NCR clients trust Dheeraj Shastri Ji for ex love back solutions, husband-wife disputes, intercaste love marriage guidance, and breakup recovery through proven Vedic astrology.',
    keywords: ['relationship astrologer Delhi', 'ex love back Delhi', 'love problem solution Delhi NCR'],
  },
  {
    slug: 'love-astrologer-pune',
    city: 'Pune',
    region: 'Maharashtra',
    focus: 'Love Astrologer',
    title: 'Love Astrologer in Pune | Love Problem Solution – Dheeraj Shastri Ji',
    description: 'Best love problem solution astrologer in Pune. Ex love back, breakup help, vashikaran & marriage remedies. Marathi & Hindi consultation.',
    h1: 'Love Astrologer in Pune – प्रेम समस्या & Ex Love Back Expert',
    intro: 'Pune residents seeking प्रेम समस्या उपाय consult Dheeraj Shastri Ji online via WhatsApp. Expert in relationship astrology, vashikaran, love marriage, and emotional healing.',
    keywords: ['love problem solution Pune', 'love astrologer Pune', 'प्रेम समस्या ज्योतिष Pune'],
  },
  {
    slug: 'love-astrologer-bangalore',
    city: 'Bangalore',
    region: 'Karnataka',
    focus: 'Love Astrologer',
    title: 'Love Astrologer in Bangalore | Ex Love Back Specialist – Dheeraj Shastri Ji',
    description: 'Online love astrologer for Bangalore & Karnataka. Ex love back solution, breakup help, relationship guidance & vashikaran specialist.',
    h1: 'Love Astrologer in Bangalore – Relationship & Ex Love Back Expert',
    intro: 'Bangalore clients connect with Dheeraj Shastri Ji for love back astrology, breakup recovery, and marriage problem remedies through secure online WhatsApp consultation.',
    keywords: ['love astrologer Bangalore', 'vashikaran specialist Bangalore', 'ex love back Bangalore'],
  },
  {
    slug: 'ex-love-back-specialist-india',
    city: 'India',
    region: 'Pan India',
    focus: 'Ex Love Back',
    title: 'Ex Love Back Specialist India | Love Back Astrologer – Dheeraj Shastri Ji',
    description: 'India\'s trusted ex love back specialist. How to get ex back, pyar wapas kaise laye, vashikaran & breakup solution. Online 24/7 across India & worldwide.',
    h1: 'Ex Love Back Specialist India – Love Back Astrologer Online',
    intro: 'How to get your ex back? Dheeraj Shastri Ji is a renowned ex love back specialist serving all India. Consult in English, Hindi, Marathi & Hinglish. प्यार वापस कैसे लाएं | pyar wapas kaise laye.',
    keywords: ['ex love back specialist', 'love back astrologer India', 'how to get ex back', 'pyar wapas kaise laye'],
  },
]

export function getLocationPage(slug) {
  return LOCATION_PAGES.find((p) => p.slug === slug) ?? null
}
